### ISSUE TITLE
FATFS SUPPORT?

### ISSUE THREAD

**Issue by scott-olero** [siara-cc/sqlite_micro_logger_arduino#3]
Trying to use this with Texas instruments TIVA C and FatFs 
Is there an example with FatFs?

**Comment by scott-olero** [comment]
no reply

**Comment by siara-cc** [comment]
@scott-olero  Sorry I saw this just now as I was not a watcher for this repo and I was not getting notifications.

I didn't make an example for FatFs, but it should not be too difficult to change one of the examples. Let me know if you are still looking for it.
